### ISSUE TITLE
 I have set up a service account as required, but I still can't work

### ISSUE THREAD

**Issue by tttlkkkl** [micro/go-plugins#400]
### the micre server logs:
```json
 {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"pods is forbidden: User \"system:serviceaccount:dev:micro-services\" cannot patch resource \"pods\" in API group \"\" in the namespace \"dev\"","reason":"Forbidden","details":{"kind":"pods"},"code":403}
```
### and my account yaml:
```yaml
# go-micro kubernetes 服务注册与发现 RBAC
apiVersion: v1
kind: ServiceAccount
metadata:
  name: micro-services
  namespace: dev
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: micro-registry
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - list
  - patch
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: micro-registry
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: micro-registry
subjects:
- kind: ServiceAccount
  name: micro-services
  namespace: dev
```
and my kubernetes version is v1.12.
please help me, thank you.

**Comment by amrnt** [comment]
Hi,

this is what am using and it works just fine (I'm not sure about the kubernetes version)

```yaml
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: pod-viewer-role
  namespace: SOMENAMESPACE
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "patch", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: "pod-viewer-role-binding"
  namespace: SOMENAMESPACE
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: "pod-viewer-role"
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: micro-services
    namespace: SOMENAMESPACE
---
apiVersion: v1
automountServiceAccountToken: true
imagePullSecrets:
  - name: base-dockercfg
kind: ServiceAccount
metadata:
  name: micro-services
  namespace: SOMENAMESPACE
```

and then for your deployments:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: srv-NAME
  namespace: SOMENAMESPACE
  labels:
    app: srv-NAME
spec:
  replicas: 1
  selector:
    matchLabels:
      app: srv-NAME
  template:
    metadata:
      labels:
        app: srv-NAME
    spec:
      containers:
        - name: primary
          imagePullPolicy: IfNotPresent
          image: IMAGE
          command: CMD
      serviceAccount: micro-services
      serviceAccountName: micro-services
```

Hope this will help!
