### ISSUE TITLE
configmap source problem when value has '=' in it

### ISSUE THREAD

**Issue by tlcox3** [micro/go-plugins#406]
I have been working with the configmap source for config and noticed an issue when the value of config has an '=' everything after and including the '=' is missing when it is loaded. I have tried by loading configmap with a yaml:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: config
  namespace: test
data:
  sample: "TEST1=test\nTEST2=te=st"
```

and by loading from  a directory with the file 'sample' in it:
```
TEST1=test
TEST2=te=st
```
In both of these cases the configs load such that:
TEST1=test
TEST2=te

This appears to be due to the way the lines are split, by the '=' and the first element is used as the key and the second element is used as the value, while any additional elements are ignored.
